name: build-push
on:
  push:
    branches:
      - master
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-build
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build-push
        run: |
          docker build . --tag sevenleap/apps:check-argos
          docker push sevenleap/apps:check-argos
